on:
  push:
    branches:
    - main

jobs:
  tree_sitter_test:
    name: tree-sitter check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: renjisann/tree-sitter-check
